//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shotgun {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shotgun.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough ammo!.
        /// </summary>
        internal static string Ammo_Message {
            get {
                return ResourceManager.GetString("Ammo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundFixed {
            get {
                object obj = ResourceManager.GetObject("BackgroundFixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Block {
            get {
                return ResourceManager.GetStream("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both you and Cpu blocked.
        /// </summary>
        internal static string BlockBlock_Message {
            get {
                return ResourceManager.GetString("BlockBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You blocked and Cpu reloaded.
        /// </summary>
        internal static string BlockReload_Message {
            get {
                return ResourceManager.GetString("BlockReload_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ButtonClick {
            get {
                return ResourceManager.GetStream("ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cpu_Shell {
            get {
                object obj = ResourceManager.GetObject("Cpu_Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cpu0Shell {
            get {
                object obj = ResourceManager.GetObject("Cpu0Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cpu1Shell {
            get {
                object obj = ResourceManager.GetObject("Cpu1Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cpu2Shell {
            get {
                object obj = ResourceManager.GetObject("Cpu2Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cpu3Shell {
            get {
                object obj = ResourceManager.GetObject("Cpu3Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CpuBlock {
            get {
                object obj = ResourceManager.GetObject("CpuBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpu blocked your shot.
        /// </summary>
        internal static string CpuBlock_Message {
            get {
                return ResourceManager.GetString("CpuBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CpuNeutral {
            get {
                object obj = ResourceManager.GetObject("CpuNeutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CpuReload {
            get {
                object obj = ResourceManager.GetObject("CpuReload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CpuShoot {
            get {
                object obj = ResourceManager.GetObject("CpuShoot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CpuShotgun {
            get {
                object obj = ResourceManager.GetObject("CpuShotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name cannot contain more than 10 characters!.
        /// </summary>
        internal static string Error_NameLength {
            get {
                return ResourceManager.GetString("Error_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     You must enter a name!.
        /// </summary>
        internal static string Error_NoInput {
            get {
                return ResourceManager.GetString("Error_NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun - a round-based game similar to Rock paper scissors.                                                   
        ///Rules:
        ///In order to win, you must shoot whilst the opponent is reloading.
        ///Both player and opponent starts with an empty chamber.
        ///Each time a weapon is reloaded, it&apos;s loaded with one shell.
        ///If both player and opponent shoot, nobody win - but the shell is lost.
        ///When a player has loaded its gun with 3 shells, a fatal attack is  -      available &quot;Shotgun&quot;.                                          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Faq_Game {
            get {
                return ResourceManager.GetString("Faq_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream LaunchGame {
            get {
                return ResourceManager.GetStream("LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Lose {
            get {
                return ResourceManager.GetStream("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You got hit, Cpu win!.
        /// </summary>
        internal static string Loss_Message {
            get {
                return ResourceManager.GetString("Loss_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream MouseHover {
            get {
                return ResourceManager.GetStream("MouseHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a move!.
        /// </summary>
        internal static string NoMove_Message {
            get {
                return ResourceManager.GetString("NoMove_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Shell {
            get {
                object obj = ResourceManager.GetObject("Player_Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player0Shell {
            get {
                object obj = ResourceManager.GetObject("Player0Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player1Shell {
            get {
                object obj = ResourceManager.GetObject("Player1Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2Shell {
            get {
                object obj = ResourceManager.GetObject("Player2Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player3Shell {
            get {
                object obj = ResourceManager.GetObject("Player3Shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerBlock {
            get {
                object obj = ResourceManager.GetObject("PlayerBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You blocked Cpu&apos;s shot.
        /// </summary>
        internal static string PlayerBlock_Message {
            get {
                return ResourceManager.GetString("PlayerBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerNeutral {
            get {
                object obj = ResourceManager.GetObject("PlayerNeutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerReload {
            get {
                object obj = ResourceManager.GetObject("PlayerReload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerShoot {
            get {
                object obj = ResourceManager.GetObject("PlayerShoot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerShotgun {
            get {
                object obj = ResourceManager.GetObject("PlayerShotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Reload {
            get {
                return ResourceManager.GetStream("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reloaded and Cpu blocked.
        /// </summary>
        internal static string ReloadBlock_Message {
            get {
                return ResourceManager.GetString("ReloadBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both you and Cpu reloaded.
        /// </summary>
        internal static string ReloadReload_Message {
            get {
                return ResourceManager.GetString("ReloadReload_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Shoot {
            get {
                return ResourceManager.GetStream("Shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Shotgun {
            get {
                return ResourceManager.GetStream("Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both you and Cpu got hit, its a tie!.
        /// </summary>
        internal static string Tie_Message {
            get {
                return ResourceManager.GetString("Tie_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Win {
            get {
                return ResourceManager.GetStream("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpu got hit, you win!.
        /// </summary>
        internal static string Win_Message {
            get {
                return ResourceManager.GetString("Win_Message", resourceCulture);
            }
        }
    }
}
